### ISSUE TITLE
连载系列3 Hexo博客乔迁Github之旅 | Pony

### ISSUE THREAD

**Issue by qq564984789** [qq564984789/qq564984789.github.io#1]
http://www.yangkai123.top/posts/3410577690/ 

 为什么要乔迁？前两节讲述的是Hexo博客在本地的搭建，这时候博客是部署在你自己电脑上的，也只有用你的电脑才能访问这个博客，我把它叫本地博客。在网络时代，我们都希望自己的博客可以联网访问。我所谓的网络博客，就是将博客部署在一台具有公网IP地址

**Comment by CCIT18081430137** [comment]
老师你好，我想请问一下，为什么最后一步hexo d的部署总是不成功，我检查了_config.yml文件，空格是对的，仓库id也是对的，这是什么原因？

**Comment by qq564984789** [comment]
> @CCIT18081430137
先要保证本地和GIhub网站可以通过ssh或者http连接上。前提是如果你采用ssh连接，那么要将本机的秘钥存放在Github上，这样本机才被Github信任。

**Comment by CCIT18081430137** [comment]
> @qq564984789
> > @CCIT18081430137
> 先要保证本地和GIhub网站可以通过ssh或者http连接上。前提是如果你采用ssh连接，那么要将本机的秘钥存放在Github上，这样本机才被Github信任。

已经解决了，可以上传了，谢谢老师

**Comment by ccit18081430101** [comment]
老师你好，我想请问一下，为什么每次我hexo初始化后总是无法出现博客中说的那句话，而是[43mWARN [49m git clone failed. Copying data instead
[43mWARN [49m Failed to install dependencies. Please run 'npm install' manually!这句话

**Comment by qq564984789** [comment]
> @ccit18081430101
> 老师你好，我想请问一下，为什么每次我hexo初始化后总是无法出现博客中说的那句话，而是[43mWARN [49m git clone failed. Copying data instead
> [43mWARN [49m Failed to install dependencies. Please run 'npm install' manually!这句话

首先确定博客在本地是否可以预览。如果可以，表示Hexo的安装是成功的。否则就是git安装和Github配置的问题了。

**Comment by CCIT18081430117** [comment]
老师，我想请教下为什么我的hexo最后打开只有纯文本

**Comment by ghost** [comment]
老师你好，我想问一下你用的是什么服务器，我想多了解一些。

**Comment by ccit18081430101** [comment]
老师，您好，我想请问一个问题，为何每次我最后的hexo d都没有办法执行成功，有时是直接出错，有几次是出来了但是网页打开之后仅仅只是字符

**Comment by ccit18081430101** [comment]
老师，您好，我想请问一个问题，为何每次我最后的hexo d都没有办法执行成功，有时是直接出错，有几次是出来了但是网页打开之后仅仅只是字符

**Comment by ghost** [comment]
Q 孙阔:
error: failed to push some refs to 'git@github.com:jianju-s/jiangju-s.github.io.git'
老师这是什么原因

**Comment by qq564984789** [comment]
> @CCIT18081430131
> 老师你好，我想问一下你用的是什么服务器，我想多了解一些。

我用的是腾讯云服务器，在课程通知文档中有链接。相对阿里云便宜些。

**Comment by qq564984789** [comment]
> @jiangju99
> Q 孙阔:
> error: failed to push some refs to 'git@github.com:jianju-s/jiangju-s.github.io.git'
> 老师这是什么原因
根据错误提示的意思，你是要把本地的文件推送到Github仓库？估计是你在Git上面还有些问题，应该还有一些其他错误提示语你没放上来吧？需要有全面的错误提示才能分析。

**Comment by qq564984789** [comment]
> @CCIT18081430117
> 老师，我想请教下为什么我的hexo最后打开只有纯文本

在浏览器中输入网址看到的是纯文本？

**Comment by qq564984789** [comment]
> @ccit18081430101
> 老师，您好，我想请问一个问题，为何每次我最后的hexo d都没有办法执行成功，有时是直接出错，有几次是出来了但是网页打开之后仅仅只是字符

Hexo在本地可以预览成功吗？

**Comment by ghost** [comment]
Q 孙阔:
D:\blog\jiangjun>

D:\blog\jiangjun>hexo g

INFO  Start processing

INFO  Files loaded in 75 ms

INFO  0 files generated in 32 ms


D:\blog\jiangjun>hexo d

D:\blog\jiangjun>

老师 输入hexo d 之后没反应 会在弹出D:\blog\jiangjun> 是什么原因

**Comment by qq564984789** [comment]
> @jiangju99
> Q 孙阔:
> D:\blog\jiangjun>
> 
> D:\blog\jiangjun>hexo g
> 
> INFO  Start processing
> 
> INFO  Files loaded in 75 ms
> 
> INFO  0 files generated in 32 ms
> 
> 
> D:\blog\jiangjun>hexo d
> 
> D:\blog\jiangjun>
> 
> 老师 输入hexo d 之后没反应 会在弹出D:\blog\jiangjun> 是什么原因

1、首先确保博客在本地可以显示；
2、如果第1部成功，则看下根目录下的config文件中deploy标签后面的配置，是否有空格。

**Comment by ghost** [comment]
> @qq564984789
> > @jiangju99
> > Q 孙阔:
> > D:\blog\jiangjun>
> > 
> > D:\blog\jiangjun>hexo g
> > 
> > INFO  Start processing
> > 
> > INFO  Files loaded in 75 ms
> > 
> > INFO  0 files generated in 32 ms
> > 
> > 
> > D:\blog\jiangjun>hexo d
> > 
> > D:\blog\jiangjun>
> > 
> > 老师 输入hexo d 之后没反应 会在弹出D:\blog\jiangjun> 是什么原因
> 
> 1、首先确保博客在本地可以显示；
> 2、如果第1部成功，则看下根目录下的config文件中deploy标签后面的配置，是否有空格。

**Comment by ghost** [comment]
后面有空格 但是输入还是没有反应  出现的还是 hexo d

**Comment by ger233** [comment]
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'TIM@LAPTOP-B723OBBF.(none)')
error: src refspec HEAD does not match any
error: failed to push some refs to 'git@github.com:ger233/ger233.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (C:\blog\node_modules\hexo-util\lib\spawn.js:51:21)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.cp.emit (C:\blog\node_modules\cross-spawn\lib\enoent.js:34:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
输入hexo d总是出现这样的错误，请问是什么原因？

**Comment by julywxx** [comment]
老师我想问您一下。我刚做到博文三刚开始部分，发现我的仓库不具备网页展示功能，怎么解决呢？
